### ISSUE TITLE
🐞 [Bug]: Confusing UI for Bluetooth

### ISSUE THREAD

**Issue by devinrsmith** [meshtastic/Meshtastic-Apple#1025]
### Firmware Version

2.5.15.79da236

### What did you do?

I originally thought that the Bluetooth on a new radio I got was busted; the device was not appearing in the iOS Bluetooth settings screen, nor on the Meshtastic Bluetooth screen. I had an existing radio connected, so I figured the new BT was broken. I even sent the device back to the manufacturer :/.

Then, the manufacturer told me that "everything with Bluetooth seems to be fine", and so I did some more investigation and came across https://www.reddit.com/r/meshtastic/comments/1b3b5r4/meshtastic_app_with_multiple_radios/:

> on the Bluetooth tab, on the Connected Radio, swipe left, tap disconnect.

This was not obvious to me.

There seems to be a related issue / comment talking about "documentation tip" https://github.com/meshtastic/Meshtastic-Apple/issues/1019#issuecomment-2547065095, but it looks like that "documentation tip" is a one-time warning and I must have immediately dismissed it a while ago when I connected my first radio.

It would be very beneficial to have a clearer UX with a permanent "Available Radios" section, or a permanent message "to enable Available Radios, please disconnect your existing radio". 

### Expected Behavior

Some design element(s) that would have prevented this sort of issue from happening.

### Participation

- [ ] I am willing to submit a pull request for this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by garthvh** [comment]
The tip is not a one time item, you have to close it

**Comment by devinrsmith** [comment]
This is how it looks for me; I haven't closed any tips. Maybe there is a bug where the tip is not displayed in some cases?

![image](https://github.com/user-attachments/assets/b350135f-8920-48b0-b0c8-32429750801e)

**Comment by garthvh** [comment]
You closed it at some point, the goal is to stay simply connected to a single node.  If you delete and re-install the app it will return.

**Comment by devinrsmith** [comment]
Got it.

I assume a lot of users see that documentation tip exactly once when they first open the Meshtastic app and immediately close it. And then, maybe a month or two down the line, they get a second radio but can't figure out why it's not working. At least, it's happened to me, and it seems like other people as well.

I think there could be some simple UI elements that make this less confusing. Would some sort of persistent note along the lines of "to enable Available Radios, please disconnect your existing radio" make sense? Or, maybe a collapsible "Available Radios" section that shows that message when you expand it? I'm not a UI designer, but I'm trying to make sure others don't fall into the trap that I did.

**Comment by garthvh** [comment]
The Bluetooth UI has been completely redesigned with a dedicated **Connect tab** (replacing the old Bluetooth settings flow). The Connect tab:

- Shows your currently connected device with signal strength, battery level, and connection status at the top
- Lists all other discovered BLE devices below so you can clearly see what's available
- Makes it obvious when you're connected to a different device vs. scanning for new ones
- Provides a clear connect/disconnect flow

The old pattern of needing to know about iOS Bluetooth settings to discover devices has been replaced by this in-app device discovery. The device that was invisible in this issue (because another device was already connected) would now appear in the 'Other Devices' list in the Connect tab.
